name: ArgumentsCollector
version: 1.5
api-version: 1.17
folia-supported: true
author: Learting
main: cc.globalserver.ArgumentsCollector.Main
commands:
  ac:
    description: Interactive Command Implement
    usage: /<command> (-f) <cmd> <msg1> <msg2> ... <msgx>
  ac_click:
    description: internal use
    usage: /<command>
